---
title: "Global Land Use"
author: "Mandy Liesch"
date: "2025-03-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(plotly)
library(tidyterra)

PastLU<-read_csv("L125.LC_bm2_R_LT_Yh_GLU.csv")
LUFile<-read_csv("s84_land_cover_basin.csv")
GCAM_Basin_ID<-read_csv("GCAM_Basin_Key.csv")


```

```{r}
#Merge Historic Data with GCAM Basin IDs
Hist_LU<-merge(GCAM_Basin_ID, PastLU, by.x=c("GLU_code", "reg_id"), by.y=c("GLU", "GCAM_region_ID"), ALL=TRUE)

#Merge BasinID file with Future GCAM Data
Fut_LU<-merge(GCAM_Basin_ID, LUFile, by.x=c("GLU_Name", "reg_nm"), by.y=c("riverBasin", "region"), ALL=TRUE)


```


# Past Land Use

```{r}
PastLU_Recode <- PastLU %>% 
  mutate(Land_Type = recode(Land_Type, "UrbanLand" = "OtherNotArable", "Tundra"= "OtherNotArable", "RockIceDesert"="OtherNotArable", "HarvCropLand"="Cropland", "Pasture"="ManagedPasture", "Forest"="ManagedForest", "OtherArableLand" = "OtherArable"))

Past_Table <- PastLU_Recode  %>% group_by(Land_Type, year) %>% 
  summarise(Area = sum(value))  %>%
  mutate(totArea = Area/10) %>%
  dplyr::select(-c("Area"))

PastRefLand.plt<-ggplot(Past_Table) +
  geom_line(mapping=aes(x=year, y=totArea, color=Land_Type), lwd=2) +
  scale_color_manual(values=c("#FED439FF",  "#46732EFF", "green","#FD8CC1FF", "#D2AF81FF", "#8A9197FF",   "#F05C3BFF","#075149FF", "#370335FF"),  name="Land Use", labels=c("Cropland",  "Managed Forest", "Grassland", "Other Arable Land", "Other Not Arable", "Managed Pasture",  "Shrubland", "Unmanaged Forest", "Unmanaged Pasture")) +
  ggtitle("Past Land Use") +
  #Add the theme elements
  theme(plot.title = element_text(hjust = 0.5)) +
  #Add the labels
  labs( x='Year', y='Area (Mha)', linetype="Shock Type") 

ggplotly(PastRefLand.plt)
```

# Future Land Use

```{r}

new_Shock_LU<- LUFile  %>% 
  separate(Variable, c("Land", "LandUse", "Status")) %>%
  dplyr::select(-c("Model", "Unit"))  %>%
  filter(Land == "LandCover") %>%
  filter(LandUse!= "Total") %>%
  filter(Status != "Total"|is.na(Status)) %>%
  mutate(Status = replace_na(Status, "")) %>%
  unite(LandCover, Status, LandUse, sep="")


wide_sum_cat_LU<- new_Shock_LU %>% 
  dplyr::select(-c("Land"))  %>%
  pivot_longer(!c(scenario, region, riverBasin, LandCover), names_to=c("year"), values_to = "area") %>%
  mutate(year = as.numeric(year)) %>% 
  pivot_wider(names_from = scenario, values_from = c(area)) %>%
  mutate(DifCornShock = CORN1BG - REF) %>%
  mutate(DifSoyShock = SOY1BG - REF)

futRefLand.plt<-ggplot(wide_sum_cat_LU %>% 
                              filter(region=="WLD")) +
  geom_line(mapping=aes(x=year, y=REF, color=LandCover), lwd=2) +
  scale_color_manual(values=c("#FED439FF", "#46732EFF", "green", "#FD8CC1FF", "#D2AF81FF", "#8A9197FF", "#F05C3BFF","#075149FF", "#370335FF"),  name="Land Use", labels=c("Cropland", "Grassland", "Managed Forest", "Managed Pasture", "Other Arable Land","Other Not Arable", "Shrubland", "Unmanaged Forest", "Unmanaged Pasture")) +
  ggtitle("Future Land Use") +
  #Add the theme elements
  theme(plot.title = element_text(hjust = 0.5)) +
  #Add the labels
  labs( x='Year', y='Area (Mha)', linetype="Shock Type") 

ggplotly(futRefLand.plt)
```

# Future Land Shocks

```{r}

futShocksLand.plt<-ggplot(wide_sum_cat_LU %>% 
                              filter(region=="WLD")) +
  geom_line(mapping=aes(x=year, y=DifCornShock, color=LandCover, linetype="Corn"), lwd=2) +
  geom_line(mapping=aes(x=year, y=DifSoyShock, color=LandCover, linetype="Soy"),  lwd=2) +
  scale_color_manual(values=c("#FED439FF", "#46732EFF", "green", "#FD8CC1FF", "#D2AF81FF", "#8A9197FF", "#F05C3BFF","#075149FF", "#370335FF"),  name="Land Use", labels=c("Cropland", "Grassland", "Managed Forest", "Managed Pasture", "Other Arable Land","Other Not Arable", "Shrubland", "Unmanaged Forest", "Unmanaged Pasture")) +
  ggtitle("Future Land Emission Shocks") +
  #Add the theme elements
  #theme(plot.title = element_text(hjust = 0.5)) +
  #Add the labels
  labs( x='Year', y='Area (Mha)', linetype="Shock Type") 


ggplotly(futShocksLand.plt)

```

# Total Global Land Use Change

```{r}
world_future<-wide_sum_cat_LU %>% 
  filter(region=="WLD") %>%
  filter(year>=2020) %>%
  dplyr::select(c("LandCover", "year", "REF")) %>%
  rename("Land_Type" = "LandCover", "totArea" = "REF" )

Total_Time_Series<-rbind(Past_Table, world_future)

totLandChange.plt<-ggplot(Total_Time_Series) +
  geom_line(mapping=aes(x=year, y=totArea, color=Land_Type), lwd=2) +
  scale_color_manual(values=c("#FED439FF", "#46732EFF", "green", "#FD8CC1FF", "#D2AF81FF", "#8A9197FF", "#F05C3BFF","#075149FF", "#370335FF"),  name="Land Use", labels=c("Cropland", "Grassland", "Managed Forest", "Managed Pasture", "Other Arable Land","Other Not Arable", "Shrubland", "Unmanaged Forest", "Unmanaged Pasture")) +
  ggtitle("Global Land Use Change") +
  #Add the theme elements
  theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom") +

  #Add the labels
  labs( x='Year', y='Area (Mha)') 

ggplotly(totLandChange.plt)
```

# Region of 8 Land Use Changes

```{r}
